---
# tasks file for galaxyprojectdotorg.proftpd

- name: Install ProFTPD (apt)
  apt:
    name: "{{ item }}"
  with_items:
    - proftpd-basic
    - proftpd-mod-pgsql
    - proftpd-mod-vroot
  when: item != 'proftpd-mod-pgsql' or proftpd_galaxy_auth is defined

- name: Add include statement to proftpd.conf
  lineinfile:
    name: "{{ proftpd_config_file }}"
    regexp: "^Include {{ proftpd_config_include_dir }}"
    state: present
    insertafter: EOF
    line: "Include {{ proftpd_config_include_dir }}/*.conf"
  notify:
    - reload proftpd
